function options = define_solver_options_UB()
    % --- 1. 上界法迭代参数 ---
    options.epsilon_act = 1e-3;
    options.epsilon_sat = 1e-3;
    
    % --- 2. NLP 求解器 (fmincon) 参数 ---
    NLPTolCstr = options.epsilon_act * 1e-3;
    NLPTolStat = options.epsilon_sat * 1e-3;
    
    options.fmincon = optimoptions('fmincon', ...
        'Algorithm', 'sqp', ... 
        'Display', 'iter', ...
        'SpecifyObjectiveGradient', true, ... 
        'SpecifyConstraintGradient', true, ...
        "EnableFeasibilityMode", true, ...
        'MaxIterations', 1000,  ...
        'MaxFunctionEvaluations', 50000, ...
        'ConstraintTolerance', NLPTolCstr, ...
        'OptimalityTolerance', NLPTolStat);
end